export interface ISubdivision {
            id: number,
            code: string,
            name: string,
            longitude: string,
            latitude: string,
            fieldSurveyTerritoryId: number,
            marketId: number,
            subdivisionStatusId: number,
            surveyMethodId: number,
            activeSections: number,
            futureSections: number,
            builtOutSections: number,
            totalLots: number,
            fieldSurveyTerritoryName: string,
            marketName: string,
            marketAbbreviation: string,
            subdivisionStatusCode: string,
            surveyMethodCode: string,
            county: string,
            community: string,
            zoom17Date: string,
            zoom18Date: string,
            subdivisionGeometryId: string,
            subdivisionGeometryBoundingBoxId: string,
            subdivisionGeometryBoundaryId: string,
            subdivisionGeometryIntelligenceBoundaryId: number,
            subdivisionGeometryIntelligenceBoundaryStatusId: number,
            subdivisionGeometryIntelligenceBoundaryStatusCode: string,
            subdivisionGeometryIntelligenceBoundaryStatusChangeDate: string,
            nearMapImageDate: string,
            imageBoxId: number,
            mostRecentIPointBatchDate: string,
            iPoints: string,
            validatediPoints: string,
            subdivisionSpecificStatus: string
}

export interface ISubdivisionList {
    subdivisions:ISubdivision[]
} 